on:
  push:
    branches:
    - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: colega/colega.eu:latest
name: build-and-push-docker
